Development
Kevin-Mena/world-countries-info pull request #5
Opened 2023-04-18 12:04 UTC by Kevin-Mena

### In this World Info Webapp Project, I Completed the following:
✅ Added a home page with a list of countries that could be filtered by some parameters
✅ Added details page for the country details
✅ Added components and functionalities for both pages
✅ Fetched countries' data from an API
✅ Added styling to the components
✅ Added tests to the components
✅ Deployed the application for an online version

2023-04-18 15:27 UTC, mckent05 requested changes
Hi @Kevin-Mena, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- All unit tests are passing, well done 👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-18 15:27 UTC, mckent05 commented on src/components/CountriesList.js
> +    </div>
- Good job done so far, but your homepage is not styled according to the design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏 According to the project requirements, you are required to follow the below design guidlines:
-- Typography: font face, size, and weight
-- Layout: composition and space between elements. Please fix the composition and space between your elements 🙏 

Your project:
![awtaw4tw](https://user-images.githubusercontent.com/73607512/232822147-69694bf9-0ed8-4df5-80e3-e2b609001808.PNG)

2023-04-18 15:27 UTC, mckent05 commented on src/components/CountriesList.js
> +        />
- Your filter component does not work as expected, I tried searching for a country named `Barbados` in your application and got no result. Please fix this 🙏 . I suggest you consider making sure that both your search parameter and the country named being searched for are both in lower or uppercase letters, you can use the `toLowerCase()` method for this 🙏

2023-04-18 15:27 UTC, mckent05 commented on src/redux/detailsSlice.js
> +export default detailsReducer.reducer;
- You seem not to have used this reducer in any of your components, If so, I suggest deleting this file/reducer, as it is important to keep only necessary files in your project. Please fix this 🙏

2023-04-19 10:32 UTC, Kevin-Mena commented on src/redux/detailsSlice.js
> +export default detailsReducer.reducer;
Thank you for the suggestions,I'll implement them as required

2023-04-19 11:24 UTC, VICTOR-CHUKWU approved these changes
Hi @Kevin-Mena ,
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-04-19 11:26 UTC, merged